### ISSUE TITLE
Api mismatch?

### ISSUE THREAD

**Issue by semsitivity** [do-community/doks-monitoring#5]
Hi,
I'm running a digitalocean kubernetes cluster version 1.16.2-do.1:
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-18T14:56:51Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

But following the tutorial, I get this:
unable to recognize "xxx-cluster-monitoring_manifest.yaml": no matches for kind "StatefulSet" in version "apps/v1beta2"
unable to recognize "xxx-cluster-monitoring_manifest.yaml": no matches for kind "StatefulSet" in version "apps/v1beta2"
unable to recognize "xxx-cluster-monitoring_manifest.yaml": no matches for kind "Deployment" in version "apps/v1beta2"
unable to recognize "xxx-cluster-monitoring_manifest.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"
unable to recognize "xxx-cluster-monitoring_manifest.yaml": no matches for kind "StatefulSet" in version "apps/v1beta2"

Is there something to patch in the generated yaml file?

**Comment by hjet** [comment]
Hi @semsitivity!  Thanks for filing this issue! 

I just pushed a commit to update API versions so this issue should be resolved now. However, there is still a larger bug when using this Quickstart with 1.16 (it works fine for 1.14 & 1.15). I am going to create a separate issue so you can track progress there directly, but basically on K8S 1.16 Grafana dashboards don't work properly and the Prometheus config needs some tweaking.

**Comment by hjet** [comment]
Here's the issue you can track for a 1.16 fix: https://github.com/do-community/doks-monitoring/issues/6
